# Generated by Django 5.0.6 on 2024-08-13 12:56

import Kronosapp.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kronosapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='username',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='course',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='studyPlan',
        ),
        migrations.AddField(
            model_name='customuser',
            name='phone',
            field=models.CharField(blank=True, max_length=25, null=True, validators=[Kronosapp.models.validate_numeric]),
        ),
        migrations.AddField(
            model_name='customuser',
            name='profile_picure',
            field=models.ImageField(blank=True, null=True, upload_to='logos/'),
        ),
        migrations.AddField(
            model_name='subject',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Kronosapp.school'),
        ),
        migrations.AlterField(
            model_name='contactinformation',
            name='streetNumber',
            field=models.CharField(max_length=10, validators=[Kronosapp.models.validate_numeric]),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='document',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, validators=[Kronosapp.models.validate_numeric]),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='gender',
            field=models.CharField(blank=True, choices=[('masculino', 'Masculino'), ('femenino', 'Femenino')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='year',
            name='preceptors',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='CourseSubjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studyPlan', models.TextField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Kronosapp.course')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Kronosapp.subject')),
            ],
        ),
        migrations.AlterField(
            model_name='teachersubjectschool',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Kronosapp.coursesubjects'),
        ),
        migrations.AddField(
            model_name='event',
            name='roles',
            field=models.ManyToManyField(to='Kronosapp.role'),
        ),
    ]
