# Generated by Django 5.1 on 2024-08-13 15:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kronosapp', '0002_role_alter_customuser_managers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='school',
        ),
        migrations.AddField(
            model_name='subject',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Kronosapp.course'),
        ),
        migrations.AddField(
            model_name='subject',
            name='studyPlan',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='year',
            name='number',
            field=models.CharField(max_length=1),
        ),
    ]
