# Generated by Django 5.1.1 on 2024-10-01 13:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kronosapp', '0002_alter_customuser_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedules',
            name='tssId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Kronosapp.teachersubjectschool'),
        ),
    ]
