# Generated by Django 5.0.6 on 2024-08-16 14:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kronosapp', '0003_remove_subject_school_subject_course_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='profile_picure',
            new_name='profile_picture',
        ),
        migrations.AlterField(
            model_name='teachersubjectschool',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Kronosapp.subject'),
        ),
    ]
