# Generated by Django 5.1 on 2024-08-15 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kronosapp', '0003_remove_subject_school_subject_course_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='course',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='studyPlan',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='weeklyHours',
        ),
        migrations.AddField(
            model_name='coursesubjects',
            name='weeklyHours',
            field=models.IntegerField(default=3),
            preserve_default=False,
        ),
    ]
