# Generated by Django 5.1 on 2024-08-15 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Kronosapp', '0004_remove_subject_course_remove_subject_studyplan_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teachersubjectschool',
            old_name='subject',
            new_name='coursesubjects',
        ),
    ]
