# Generated by Django 5.0.4 on 2024-04-23 13:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kronosapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schools',
            name='phoneNumber',
        ),
        migrations.RemoveField(
            model_name='users',
            name='cellphone',
        ),
        migrations.AlterField(
            model_name='schools',
            name='contactInfoId',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Kronosapp.contactinformation'),
        ),
        migrations.AlterField(
            model_name='users',
            name='contactInfoId',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Kronosapp.contactinformation'),
        ),
    ]
