# Generated by Django 5.0.4 on 2024-04-23 14:55

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kronosapp', '0002_remove_schools_phonenumber_remove_users_cellphone_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('userId', models.IntegerField(primary_key=True, serialize=False)),
                ('firstName', models.CharField(max_length=255)),
                ('lastName', models.CharField(max_length=255)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('document', models.CharField(max_length=255)),
                ('hoursToWork', models.IntegerField()),
                ('email_verified', models.BooleanField(default=False)),
                ('verification_token', models.UUIDField(default=uuid.uuid4)),
                ('contactInfoId', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Kronosapp.contactinformation')),
                ('documentTypeId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Kronosapp.documenttypes')),
                ('nationalityId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Kronosapp.nationalities')),
                ('roleId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Kronosapp.roles')),
            ],
        ),
        migrations.AlterField(
            model_name='teacheravailability',
            name='teacherId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Kronosapp.user'),
        ),
        migrations.AlterField(
            model_name='teacherevent',
            name='teacherId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Kronosapp.user'),
        ),
        migrations.AlterField(
            model_name='teachersubjectschool',
            name='teacherId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Kronosapp.user'),
        ),
        migrations.DeleteModel(
            name='Users',
        ),
    ]
