# Generated by Django 5.0.4 on 2024-05-16 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kronosapp', '0003_alter_school_logo_alter_subject_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='color1',
            field=models.CharField(default='000000', max_length=12),
        ),
        migrations.AddField(
            model_name='customuser',
            name='color2',
            field=models.CharField(default='111111', max_length=12),
        ),
        migrations.AddField(
            model_name='customuser',
            name='color3',
            field=models.CharField(default='222222', max_length=12),
        ),
        migrations.AddField(
            model_name='customuser',
            name='dark_mode',
            field=models.BooleanField(default=False),
        ),
    ]
